### ISSUE TITLE
Trouble disabling

### ISSUE THREAD

**Issue by jakirkham** [coderanger/nightlies#16]
Am trying to disable nightli.es on a repo where it is no longer needed, but the Heroku app fails to load. If I had to guess, it is because there are too many repos to load on to a single page. Would be happy if either this was disabled by some other way or if the page could load so that I could do it myself.

**Comment by coderanger** [comment]
Hmm, it seems to be loading okay for me. It's a free-tier app so the first request after the app sleeps can sometimes time out, but the second should usually work. If that doesn't fix it, what's the repo you are trying to remove and I can just manually nuke it from the DB.

**Comment by jakirkham** [comment]
Yeah would imagine it works fine for most (and use to for me). Though I have 1000s of repos under my account and associated orgs now. So it might cause it to choke. Have given it a few tries. Don't want to mess it up if I can avoid it.

Sure the repo is [conda-forge/conda-forge.github.io]( https://github.com/conda-forge/conda-forge.github.io ).

**Comment by coderanger** [comment]
Hah, that would certainly be more load on my terrible code :) I wiped that row manually so this should be all set. If you need any other added/removed, just let me know.

**Comment by jakirkham** [comment]
Perfect. Thanks.

No worries. There have been CIs that have been struggling with loading such a list even when nightli.es was doing fine. So you must have done something right in that code. 😉
