### ISSUE TITLE
Footer hides part of the page (Chrome)

### ISSUE THREAD

**Issue by remram44** [coderanger/nightlies#2]
On Chrome, the footer doesn't stay at the bottom of the window, it scrolls with the page. This hides one entry from the list if it is long enough.

Screenshots:
![1](https://cloud.githubusercontent.com/assets/426784/9315615/1f82a3a4-44fe-11e5-9eab-597e8992bf56.png)
![2](https://cloud.githubusercontent.com/assets/426784/9315617/21fe72de-44fe-11e5-8286-d39a1f864e63.png)

**Comment by coderanger** [comment]
I have battled the fearsome CSS demons (I think)! Thanks for the report.
